[package]
name = "exclusion-merkle-cbt"
version = "0.1.0"
edition = "2018"
description = "Complete Binary Merkle Tree for verify exclusion"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
merkle-cbt = "0.3.0"